#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════
#  entrypoint.sh — نقطة دخول Docker لـ Railway/VPS
#  ─────────────────────────────────────────────────────────────────────────
#  1. يتحقق من المتغيرات الإجبارية
#  2. يكشف IPv6 outward availability
#  3. يهيّئ WARP إذا لزم (IPv6 غير متاح)
#  4. يولّد cookies.txt مرة واحدة
#  5. يبني .env من متغيرات البيئة
#  6. يشغّل supervisord
# ═══════════════════════════════════════════════════════════════════════════
set -euo pipefail

log() { echo "[entrypoint] $(date '+%Y-%m-%d %H:%M:%S') $*"; }

# ── 1) التحقق من المتغيرات الإجبارية ──────────────────────────────────────
if [ -z "${DISCORD_TOKEN:-}" ]; then
    echo "❌ DISCORD_TOKEN مفقود!"
    echo "   أضفه في Railway: Variables > DISCORD_TOKEN"
    exit 1
fi

if [ -z "${CLIENT_ID:-}" ]; then
    echo "❌ CLIENT_ID مفقود!"
    echo "   احصل عليه من Discord Developer Portal > تطبيقك > General Information > Application ID"
    exit 1
fi

log "✅ DISCORD_TOKEN و CLIENT_ID موجودان"

# ── 1.5) ضمان وجود مجلدات حرجة (تُنشأ من Dockerfile، لكن نتأكد هنا أيضاً) ──
mkdir -p /app/database /app/cookies /app/audio_cache /app/logs /app/data
# أنشئ ملفات JSON افتراضية فارغة إذا لم تكن موجودة (لمنع أخطاء JSON parse)
[ -f /app/database/languages.json ] || echo '{}' > /app/database/languages.json
[ -f /app/database/playerState.json ] || echo '{}' > /app/database/playerState.json
log "📁 مجلدات حرية جاهزة: database/ cookies/ audio_cache/ logs/ data/"

# ── 2) كشف IPv6 outbound ─────────────────────────────────────────────────
IPV6_AVAILABLE="false"
if curl -6 -s --max-time 5 https://api64.ipify.org > /dev/null 2>&1; then
    IPV6_AVAILABLE="true"
    log "🌐 IPv6 outbound متاح (مثالي لـ Railway)"
else
    log "⚠️ IPv6 outbound غير متاح — سيتم استخدام WARP fallback"
fi

# ── 3) تحديد وضع التشغيل ──────────────────────────────────────────────────
CONNECTION_MODE="${YT_CONNECTION_MODE:-auto}"
log "🔗 وضع الاتصال: ${CONNECTION_MODE} | IPv6: ${IPV6_AVAILABLE}"

NEED_WARP="false"
if [ "${CONNECTION_MODE}" = "warp" ]; then
    NEED_WARP="true"
elif [ "${CONNECTION_MODE}" = "auto" ] && [ "${IPV6_AVAILABLE}" = "false" ]; then
    NEED_WARP="true"
fi

# ── 4) تهيئة WARP (إذا لزم) ────────────────────────────────────────────────
# ملاحظة هامة لـ Railway: حتى لو كان IPv6 متاح، wireproxy سيحاول UDP outbound
# للمنفذ 2408 (Cloudflare WARP endpoint). Railway يحظر UDP outbound افتراضياً،
# لذا wireproxy سيفشل ويعيد المحاولة بسرعة حتى يدخل FATAL state.
# الحل: لا نشغّل wireproxy إطلاقاً إذا IPv6 متاح.
if [ "${NEED_WARP}" = "true" ] && [ "${ELMINYAWE_ENABLED:-true}" = "true" ]; then
    log "🌐 تهيئة Cloudflare WARP tunnel..."
    if /opt/scripts/warp-setup.sh; then
        log "✅ WARP جاهز"
        # فعّل wireproxy في supervisord
        sed -i 's/^autostart=false \(# wireproxy\)/autostart=true # wireproxy/' /etc/supervisor/conf.d/supervisord.conf 2>/dev/null || true
    else
        log "⚠️ فشل WARP — البوت سيعمل بدون proxy"
        # عطّل wireproxy نهائياً
        sed -i 's/^autostart=true \(# wireproxy\)/autostart=false # wireproxy/' /etc/supervisor/conf.d/supervisord.conf 2>/dev/null || true
    fi
else
    log "⏭️ تخطّي WARP — الاتصال المباشر كافٍ (IPv6 متاح)"
    # عطّل wireproxy نهائياً في supervisord
    sed -i 's/^autostart=true \(# wireproxy\)/autostart=false # wireproxy/' /etc/supervisor/conf.d/supervisord.conf 2>/dev/null || true
fi

# ── 5) توليد .env من متغيرات البيئة ─────────────────────────────────────
log "📝 توليد /app/.env..."
# 🔒 Defense: if STATUS env var contains "beatra" (from old Railway config), override it.
if echo "$STATUS" | grep -qi beatra; then
    log "🔒 [Defense] Detected STATUS=\"$STATUS\" contains 'beatra', overriding to 'Dev : ELMINYAWE'"
    STATUS="Dev : ELMINYAWE"
fi
STATUS=${STATUS:-Dev : ELMINYAWE}
# Force-export to environment for the bot process
export STATUS

cat > /app/.env <<EOF
# Auto-generated by entrypoint.sh
# ملاحظة: مفاتيح Spotify مدمجة في config.js ولا تحتاج لإضافتها هنا

DISCORD_TOKEN=${DISCORD_TOKEN}
CLIENT_ID=${CLIENT_ID}
GUILD_ID=${GUILD_ID:-}

# Spotify (مدمجة افتراضياً في الكود — يمكنك تجاوزها هنا إن أردت)
SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID:-}
SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET:-}
SPOTIFY_MARKET=${SPOTIFY_MARKET:-US}

# Genius (optional - for lyrics)
GENIUS_CLIENT_ID=${GENIUS_CLIENT_ID:-}
GENIUS_CLIENT_SECRET=${GENIUS_CLIENT_SECRET:-}

# Bot Settings — STATUS is forced to "Dev : ELMINYAWE" defensively
EMBED_COLOR=${EMBED_COLOR:-#FF6B6B}
STATUS=${STATUS}
DEFAULT_VOLUME=${DEFAULT_VOLUME:-100}
MAX_QUEUE_SIZE=${MAX_QUEUE_SIZE:-100}
MAX_PLAYLIST_SIZE=${MAX_PLAYLIST_SIZE:-50}

# Hybrid Commands
PREFIX=${PREFIX:-!}
ENABLE_PREFIX=${ENABLE_PREFIX:-true}
ENABLE_SLASH=${ENABLE_SLASH:-true}
PREFIX_ADMIN_ONLY=${PREFIX_ADMIN_ONLY:-false}

# Sharding
TOTAL_SHARDS=${TOTAL_SHARDS:-auto}
SHARD_MODE=${SHARD_MODE:-process}
SHARD_RESPAWN=${SHARD_RESPAWN:-true}

# Resilience
EMPTY_VOICE_TIMEOUT_MS=${EMPTY_VOICE_TIMEOUT_MS:-300000}
RECONNECT_TIMEOUT_MS=${RECONNECT_TIMEOUT_MS:-10000}
MAX_RECONNECT_ATTEMPTS=${MAX_RECONNECT_ATTEMPTS:-3}
CLEANUP_DELAY_MS=${CLEANUP_DELAY_MS:-2000}
AUTO_RESUME=${AUTO_RESUME:-true}
PERSIST_PLAYER_STATE=${PERSIST_PLAYER_STATE:-true}
STATE_PERSIST_DELAY_MS=${STATE_PERSIST_DELAY_MS:-3000}

# YouTube / yt-dlp
YT_CONNECTION_MODE=${CONNECTION_MODE}
YT_PLAYER_CLIENTS=${YT_PLAYER_CLIENTS:-android_music,web_safari,web,ios}
YT_JS_RUNTIMES=${YT_JS_RUNTIMES:-deno}
YT_AUTO_COOKIES_FILE=/app/cookies/cookies.txt
YT_PROXY=${YT_PROXY:-socks5://127.0.0.1:1080}
YT_COOKIES_INTERVAL_SEC=${YT_COOKIES_INTERVAL_SEC:-21600}
YOUTUBE_DL_DIR=/usr/local/bin
YOUTUBE_DL_FILENAME=yt-dlp-py

# elminyawe
ELMINYAWE_ENABLED=${ELMINYAWE_ENABLED:-true}
BGUTIL_PORT=${BGUTIL_PORT:-4416}
WARP_SOCKS_PORT=${WARP_SOCKS_PORT:-1080}
EOF
chmod 600 /app/.env
log "✅ .env جاهز (مفاتيح Spotify مدمجة في الكود)"

# ── 6) توليد cookies.txt الأولي ────────────────────────────────────────────
if [ "${ELMINYAWE_ENABLED:-true}" = "true" ]; then
    log "🍪 توليد كوكيز YouTube الأولية..."
    mkdir -p /app/cookies

    if YT_AUTO_COOKIES_FILE=/app/cookies/cookies.txt \
        python3 /opt/scripts/yt_cookies.py --once 2>&1 | head -5; then
        if [ -f /app/cookies/cookies.txt ]; then
            log "✅ cookies.txt جاهز ($(wc -l < /app/cookies/cookies.txt) سطر)"
        fi
    else
        log "⚠️ فشل توليد الكوكيز — سيُعاد المحاولة من supervisord"
    fi
fi

# ── 7) معلومات نهائية ────────────────────────────────────────────────────
# تحقق من حالة Spotify (مدمجة افتراضياً في config.js)
SPOTIFY_STATUS="✅ مفعّل (مدمج في الكود)"
if [ -n "${SPOTIFY_CLIENT_ID:-}" ] && [ -n "${SPOTIFY_CLIENT_SECRET:-}" ]; then
    SPOTIFY_STATUS="✅ مفعّل (مخصص من Railway)"
elif [ -z "${SPOTIFY_CLIENT_ID:-}" ] && [ -z "${SPOTIFY_CLIENT_SECRET:-}" ]; then
    # استخدام القيم الافتراضية المدمجة في config.js
    SPOTIFY_STATUS="✅ مفعّل (مدمج في الكود)"
fi

log "🎉 MUS Bot v26.2 جاهز! — Dev: ELMINYAWE 👨‍💻"
log "   ├─ Discord: ✅"
log "   ├─ Connection: ${CONNECTION_MODE} (IPv6: ${IPV6_AVAILABLE}, WARP: ${NEED_WARP})"
log "   ├─ Spotify: ${SPOTIFY_STATUS}"
log "   ├─ Prefix commands: ${ENABLE_PREFIX:-true} (prefix=\"${PREFIX:-!}\")"
log "   ├─ Slash commands: ${ENABLE_SLASH:-true}"
log "   └─ Resilience: مفعّل"
log ""
log "🚀 تشغيل supervisord..."

# ── 8) تنفيذ CMD ──────────────────────────────────────────────────────────
exec "$@"
