#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════
#  warp-setup.sh — تهيئة Cloudflare WARP profile عبر wgcf
#  ─────────────────────────────────────────────────────────────────────────
#  يسجّل حساب WARP جديد (إذا لم يوجد) ويولّد wireproxy.conf بـ profile صالح
#  يُستدعى من entrypoint.sh قبل تشغيل wireproxy
# ═══════════════════════════════════════════════════════════════════════════
set -euo pipefail

WARP_DIR="/opt/warp"
ACCOUNT_FILE="${WARP_DIR}/wgcf-account.toml"
PROFILE_FILE="${WARP_DIR}/wgcf-profile.conf"
WIREPROXY_CONF="${WARP_DIR}/wireproxy.conf"
WARP_SOCKS_PORT="${WARP_SOCKS_PORT:-1080}"

log() { echo "[warp-setup] $(date '+%Y-%m-%d %H:%M:%S') $*"; }

# ── 1) إذا كان ملف profile مولّد مسبقاً وُجد، استخدمه (يجدد الـ entrypoint) ──
if [ -f "${PROFILE_FILE}" ] && grep -q "^PrivateKey" "${PROFILE_FILE}"; then
    log "✅ WARP profile موجود في ${PROFILE_FILE}"
else
    log "🚀 تسجيل حساب WARP جديد..."
    cd "${WARP_DIR}"
    # تسجيل جهاز جديد في Cloudflare WARP (مجاني، بدون بطاقة ائتمان)
    if ! /opt/warp/bin/wgcf register --accept-tos 2>&1; then
        log "❌ فشل التسجيل في WARP — سأحاول بدون WARP"
        exit 0
    fi
    log "✅ تم تسجيل حساب WARP"

    # توليد WireGuard profile
    if ! /opt/warp/bin/wgcf generate 2>&1; then
        log "❌ فشل توليد WireGuard profile"
        exit 1
    fi
    log "✅ تم توليد WireGuard profile"
fi

# ── 2) بناء wireproxy.conf من profile ──────────────────────────────────────
# wireproxy يحتاج [Interface] و [Peer] و [Socks5] في نفس الملف
log "🔧 بناء wireproxy.conf..."

# استخراج PrivateKey, Address, DNS من [Interface]
PRIVATE_KEY=$(grep "^PrivateKey" "${PROFILE_FILE}" | head -1 | cut -d'=' -f2 | xargs)
ADDRESS=$(grep "^Address" "${PROFILE_FILE}" | head -1 | cut -d'=' -f2 | xargs)
DNS=$(grep "^DNS" "${PROFILE_FILE}" | head -1 | cut -d'=' -f2 | xargs)

# استخراج PublicKey, AllowedIPs, Endpoint من [Peer]
PUBLIC_KEY=$(grep "^PublicKey" "${PROFILE_FILE}" | head -1 | cut -d'=' -f2 | xargs)
ALLOWED_IPS=$(grep "^AllowedIPs" "${PROFILE_FILE}" | head -1 | cut -d'=' -f2 | xargs)
ENDPOINT=$(grep "^Endpoint" "${PROFILE_FILE}" | head -1 | cut -d'=' -f2 | xargs)

# بناء ملف wireproxy.conf
cat > "${WIREPROXY_CONF}" <<EOF
# Auto-generated by warp-setup.sh — do not edit manually
# wireproxy userspace WireGuard tunnel → SOCKS5 proxy
# This routes all YouTube traffic through Cloudflare WARP (consumer IP)

[Interface]
PrivateKey = ${PRIVATE_KEY}
Address = ${ADDRESS}
DNS = ${DNS}
MTU = 1280

[Peer]
PublicKey = ${PUBLIC_KEY}
AllowedIPs = ${ALLOWED_IPS}
Endpoint = ${ENDPOINT}
PersistentKeepalive = 25

[Socks5]
BindAddress = 127.0.0.1:${WARP_SOCKS_PORT}
EOF

chmod 600 "${WIREPROXY_CONF}"
log "✅ wireproxy.conf جاهز على المنفذ ${WARP_SOCKS_PORT}"

# ── 3) اختبار صحة الإعداد ─────────────────────────────────────────────────
log "🧪 اختبار صحة wireproxy config..."
if /opt/warp/bin/wireproxy -n -c "${WIREPROXY_CONF}" 2>&1 | grep -q "Config OK"; then
    log "✅ wireproxy config صالح"
else
    log "❌ wireproxy config غير صالح"
    /opt/warp/bin/wireproxy -n -c "${WIREPROXY_CONF}" 2>&1 | head -20 || true
fi

exit 0
